# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('isActive', models.BooleanField()),
                ('category', models.CharField(choices=[('L', 'Location'), ('T', 'Transport'), ('C', 'Creature'), ('P', 'Party')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Game'),
        ),
    ]
