# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('L', 'Location'), ('T', 'Transport'), ('C', 'Creature'), ('P', 'Party'), ('O', 'Other')], max_length=1),
        ),
    ]
