# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0002_auto_20170812_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='placeholder',
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(blank=True, choices=[('L', 'Location'), ('P', 'Party'), ('C', 'Creature'), ('T', 'Transport'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='component',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='component',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='component',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='component',
            name='x',
            field=models.DecimalField(decimal_places=15, max_digits=19),
        ),
        migrations.AlterField(
            model_name='component',
            name='y',
            field=models.DecimalField(decimal_places=15, max_digits=19),
        ),
        migrations.AlterField(
            model_name='detail',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generator.Profile'),
            preserve_default=False,
        ),
    ]
