# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20170828_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sheet_url',
            field=models.URLField(null=True),
        ),
    ]
